### ISSUE TITLE
Solver failed to find an equilibrium

### ISSUE THREAD

**Issue by th3r3ald0n** [davidpoensgen/sgamesolver#2]
**Thank you for putting out this nice tool to solve games!** 

Unfortunately, I get this error message. 

Warning: "H(y0)" is not 0 (max deviation: 4.0).
   Solution might still be possible (because the first corrector step may fix this issue).
   However, it is advised to start with a better approximation for the starting point.
___
Start homotopy continuation
___
Step    25: Failure reason: Corrector step failed, and ds is already minimal.
Step    25: Continuation failed. Total time elapsed: 0:00:00
End homotopy continuation
___
The solver failed to find an equilibrium. Please refer to the manual for suggestions how to proceed. 

Maybe it is caused by the way I defined the game as I am new to the topic of stochastic games. 
Do you guys have an idea how to proceed in this case? 
Any help would be appreciated. 

Thank you :)

**Comment by davidpoensgen** [comment]
Hey!
Hard to say what could be the problem without further details - would you mind sharing the code (or table) you use to generate the game and to start the solver?
Cheers,
David

**Comment by th3r3ald0n** [comment]
Hi David, 
thanks for the quick reply. 
I think I solved the problem: In my game I do not need to discount payoffs. First, I applied a delta of 1. 
That was wrong, right? After I changed the delta to 0 the program runs fine. 
Btw, I uploaded the code here [https://github.com/th3r3ald0n/tennis_double_strategy](url).
The results surprise me, but I think they are right. 

Cheers :)

**Comment by davidpoensgen** [comment]
Hi there!

A delta of 0 means "the future does not matter at all", i.e. corresponds to complete discounting. (In that case, the players all maximize immediate payoffs only and the stochastic game is actually more like a bunch of one-shot-games, one for each state)
A delta of 1 on the other hand means the future is not discounted at all, i.e. tomorrow's payoffs are just as important as today's.

I presume the latter is actually what you wanted and mean when you say "no discounting".

Now, the equilibrium concept used in sgamesolver _generally_ requires delta < 1: The reason is that it uses "total discounted payoffs", starting from the current period, as the quantity that players try to maximize. If a delta of 1 is used here, actually these payoff streams are (generally) infinite and thus comparing the values of different actions not sensible. Continuation values being (or rather, tending to) inifinity is probably technically what is behind the errors you were getting.

I said delta is required to be <1 only in general, because under certain conditions, a discount factor of 1 is actually fine. But something else then has to ensure that the values are finite: For example, if the game structure is such that a terminating state (where no further payoffs are accrued) is reached with probability 1 eventually. Another sufficient condition is that the transition probabilities may add to less than 1 (which also represents potential termination) and technically serves the same purpose as delta < 1. 

Just glancing at the game you linked, I think you might want to go one of these routes: If a understand correctly, it is supposed to represent a game of tennis, where ball_0 has the ball in player 0's side, etc,  correct? and then the miss-states are those that rtepresent the event that one player missed the ball, so the game ends with the other side scoring a point?
In that case, one could for example set delta = 1, but set the phi's from the "missed"-states to 0. (Meaning that the game kind of ends after a miss - of course, in reality it would start again with the next serve, but as a modeling decision, one would look at the next game to be strategically independent.)
An alternative approach would be to set a delta that's high but not 1, e.g. 0.999. (just don't go overboard with this: if you set it _very_ close to 1, e.g. 0.99999999999999999999, the values might get very large, which alo might bring potential numerical problems.)

Hope that helps.
Best,
David

**Comment by th3r3ald0n** [comment]
Hi David, 

thank you so much for the extensive explanation!
You tought me a lot. 

You are completely right on what I want to achieve.
In the beginning I did set up a game which would run to infinity although I only need to focus on one point. 
I did set delta to 1, phi to 0 for the missed state and also to zero on all other rows where the point would end. 
Now it seems to work!! ...or at least, the strategies make more sense :D

If in any case you are interested on what this game is about just let me know. 

Thank you so much for your help.   

Cheers :))
